In [1]:
import os
import itertools
from types import SimpleNamespace
import numpy
import matplotlib.pyplot as pyplot
from scipy.interpolate import make_interp_spline
from shapely import geometry
import LocalModule
import boxkit

In [2]:
DsetDirs, FileTags = LocalModule.case2_time_convergence_dict()
Results = dict()
for key in DsetDirs:
    Datasets = LocalModule.read_datasets(DsetDirs[key], FileTags[key])
    Results[key] = numpy.array([LocalModule.process_dataset(Dataset) for Dataset in Datasets])
    
Indices=[]
for time in Results["Case2/h40"][:,0]:
    Indices += list(numpy.where(abs(Results["Case2/h320"][:,0]-time)<1e-4)[0])

In [3]:
Results["Case2/h320"][Indices,0]

array([0.        , 0.10000078, 0.20000078, 0.3       , 0.4       ,
       0.5       , 0.6       , 0.7       , 0.8       , 0.9       ,
       1.        , 1.1       , 1.2       , 1.3       , 1.4       ,
       1.5       , 1.6       , 1.7       , 1.8       , 1.9       ,
       2.        , 2.1       , 2.2       , 2.30000078, 2.40000078,
       2.50000078, 2.60000078, 2.70000078, 2.80000078, 2.90000078,
       3.00000078, 3.10000078, 3.20000078, 3.30000078, 3.40000078,
       3.50000078, 3.60000078, 3.70000078, 3.80000078, 3.90000078,
       4.00000078, 4.10000078, 4.20000078, 4.30000078, 4.40000078,
       4.50000078, 4.60000078, 4.70000078, 4.80000078, 4.90000078,
       5.00000078])

In [4]:
Error = {}

Error["Case2/h40"] = numpy.abs((Results["Case2/h320"][Indices,:]-Results["Case2/h40"]))
Error["Case2/h80"] = numpy.abs((Results["Case2/h320"][Indices,:]-Results["Case2/h80"]))
Error["Case2/h160"] = numpy.abs((Results["Case2/h320"][Indices,:]-Results["Case2/h160"]))

# for key in ["Case2/h40", "Case2/h80", "Case2/h160"]:
#     Error[key] = numpy.zeros([5,1], dtype=float)
    
#     for var in range(5):
#         for i in range (len(Results[key])):
#             Error[key][var] = Error[key][var] + (Results[key][i,var]-Results["Case2/h320"][i,var])**2

In [5]:
numpy.max(Error["Case2/h40"], axis=0)

array([4.99999988e-05, 1.58906250e-01, 1.77214783e-01, 1.17361634e-01,
       7.30191644e-02])

In [6]:
numpy.max(Error["Case2/h80"], axis=0)

array([1.24999891e-05, 8.71875000e-02, 1.87229997e-01, 1.21283000e-01,
       5.68599202e-02])

In [7]:
numpy.max(Error["Case2/h160"], axis=0)

array([3.12499854e-06, 4.39062500e-02, 1.64412953e-01, 9.06417935e-02,
       3.15973831e-02])