In [1]:
import os
import itertools
from types import SimpleNamespace
import numpy
import matplotlib.pyplot as pyplot
from scipy.interpolate import make_interp_spline
from shapely import geometry
import LocalModule
import boxkit

In [2]:
DsetDirs, FileTags = LocalModule.case1_time_convergence_dict()
Results = dict()
for key in DsetDirs:
    Datasets = LocalModule.read_datasets(DsetDirs[key], FileTags[key])
    Results[key] = numpy.array([LocalModule.process_dataset(Dataset) for Dataset in Datasets])

In [3]:
Results["Case1/h320"][:,0]

array([0.        , 0.1       , 0.20003906, 0.3       , 0.4       ,
       0.5       , 0.6       , 0.70003906, 0.80003906, 0.90003906,
       1.00003906, 1.10003906, 1.20003906, 1.30003906, 1.40003906,
       1.50003906, 1.60003906, 1.70003906, 1.80003906, 1.90003906,
       2.00003906, 2.10003906, 2.20003906, 2.30003906, 2.40003906,
       2.50003906, 2.60003906, 2.70003906, 2.80003906, 2.90003906,
       3.00003906, 3.10003906, 3.20003906, 3.30003906, 3.40003906,
       3.50003906, 3.60003906, 3.70003906, 3.80003906, 3.90003906,
       4.00003906, 4.10003906, 4.20003906, 4.30003906, 4.40003906,
       4.50003906, 4.60003906, 4.70003906, 4.80003906, 4.90003906,
       5.00003906])

In [4]:
ErrorInf = {}
ErrorL2 = {}
ErrorL1 = {}

ErrorInf["Case1/h40"] = numpy.max(numpy.abs((Results["Case1/h320"]-Results["Case1/h40"])), axis=0)
ErrorInf["Case1/h80"] = numpy.max(numpy.abs((Results["Case1/h320"]-Results["Case1/h80"])), axis=0)
ErrorInf["Case1/h160"] = numpy.max(numpy.abs((Results["Case1/h320"]-Results["Case1/h160"])), axis=0)

ErrorL2["Case1/h40"] = numpy.sqrt(numpy.sum((Results["Case1/h320"]-Results["Case1/h40"])**2, axis=0))
ErrorL2["Case1/h80"] = numpy.sqrt(numpy.sum((Results["Case1/h320"]-Results["Case1/h80"])**2, axis=0))
ErrorL2["Case1/h160"] = numpy.sqrt(numpy.sum((Results["Case1/h320"]-Results["Case1/h160"])**2, axis=0))

ErrorL1["Case1/h40"] = numpy.sum(numpy.abs(Results["Case1/h320"]-Results["Case1/h40"]), axis=0)
ErrorL1["Case1/h80"] = numpy.sum(numpy.abs(Results["Case1/h320"]-Results["Case1/h80"]), axis=0)
ErrorL1["Case1/h160"] =numpy.sum(numpy.abs(Results["Case1/h320"]-Results["Case1/h160"]), axis=0)

In [5]:
print(numpy.log10(ErrorInf["Case1/h40"]/ErrorInf["Case1/h80"])/numpy.log10(2))
print(numpy.log10(ErrorInf["Case1/h80"]/ErrorInf["Case1/h160"])/numpy.log10(2))

[2.         1.32853908 1.21575185 2.03029144 1.11011863]
[ 2.          1.24567036  1.18901862  0.55078591 -0.01171224]


In [6]:
print(numpy.log10(ErrorL2["Case1/h40"]/ErrorL2["Case1/h80"])/numpy.log10(2))
print(numpy.log10(ErrorL2["Case1/h80"]/ErrorL2["Case1/h160"])/numpy.log10(2))

[2.26897785 1.17623268 1.26170911 1.76932191 0.79749456]
[2.19745784 1.5987934  1.36563523 0.30278047 0.09163416]


In [7]:
print(numpy.log10(ErrorL1["Case1/h40"]/ErrorL1["Case1/h80"])/numpy.log10(2))
print(numpy.log10(ErrorL1["Case1/h80"]/ErrorL1["Case1/h160"])/numpy.log10(2))

[2.42502159 1.1688714  1.22955597 1.67095129 0.63863662]
[2.02217137 1.64175458 1.41151217 0.18364942 0.20439303]
