In [1]:
import os
import itertools
from types import SimpleNamespace
import numpy
import matplotlib.pyplot as pyplot
from scipy.interpolate import make_interp_spline
from shapely import geometry
import LocalModule
import boxkit

In [2]:
DsetDirs, FileTags = LocalModule.case2_time_convergence_dict()
Results = dict()
for key in DsetDirs:
    Datasets = LocalModule.read_datasets(DsetDirs[key], FileTags[key])
    Results[key] = numpy.array([LocalModule.process_dataset(Dataset) for Dataset in Datasets])
    
Indices=[]
for time in Results["Case2/h40"][:,0]:
    Indices += list(numpy.where(abs(Results["Case2/h320"][:,0]-time)<1e-4)[0])

In [3]:
Results["Case2/h320"][Indices,0]

array([0.        , 0.10000078, 0.20000078, 0.3       , 0.4       ,
       0.5       , 0.6       , 0.7       , 0.8       , 0.9       ,
       1.        , 1.1       , 1.2       , 1.3       , 1.4       ,
       1.5       , 1.6       , 1.7       , 1.8       , 1.9       ,
       2.        , 2.1       , 2.2       , 2.30000078, 2.40000078,
       2.50000078, 2.60000078, 2.70000078, 2.80000078, 2.90000078,
       3.00000078, 3.10000078, 3.20000078, 3.30000078, 3.40000078,
       3.50000078, 3.60000078, 3.70000078, 3.80000078, 3.90000078])

In [4]:
ErrorInf = {}
ErrorL2 = {}
ErrorL1 = {}

ErrorInf["Case2/h40"] = numpy.max(numpy.abs((Results["Case2/h320"][Indices,:]-Results["Case2/h40"])), axis=0)
ErrorInf["Case2/h80"] = numpy.max(numpy.abs((Results["Case2/h320"][Indices,:]-Results["Case2/h80"])), axis=0)
ErrorInf["Case2/h160"] = numpy.max(numpy.abs((Results["Case2/h320"][Indices,:]-Results["Case2/h160"])), axis=0)

ErrorL2["Case2/h40"] = numpy.sqrt(numpy.sum((Results["Case2/h320"][Indices,:]-Results["Case2/h40"])**2, axis=0))
ErrorL2["Case2/h80"] = numpy.sqrt(numpy.sum((Results["Case2/h320"][Indices,:]-Results["Case2/h80"])**2, axis=0))
ErrorL2["Case2/h160"] = numpy.sqrt(numpy.sum((Results["Case2/h320"][Indices,:]-Results["Case2/h160"])**2, axis=0))

ErrorL1["Case2/h40"] = numpy.sum(numpy.abs(Results["Case2/h320"][Indices,:]-Results["Case2/h40"]), axis=0)
ErrorL1["Case2/h80"] = numpy.sum(numpy.abs(Results["Case2/h320"][Indices,:]-Results["Case2/h80"]), axis=0)
ErrorL1["Case2/h160"] =numpy.sum(numpy.abs(Results["Case2/h320"][Indices,:]-Results["Case2/h160"]), axis=0)

# for key in ["Case2/h40", "Case2/h80", "Case2/h160"]:
#     Error[key] = numpy.zeros([5,1], dtype=float)
    
#     for var in range(5):
#         for i in range (len(Results[key])):
#             Error[key][var] = Error[key][var] + (Results[key][i,var]-Results["Case2/h320"][i,var])**2

In [5]:
print(numpy.log10(ErrorInf["Case2/h40"]/ErrorInf["Case2/h80"])/numpy.log10(2))
print(numpy.log10(ErrorInf["Case2/h80"]/ErrorInf["Case2/h160"])/numpy.log10(2))

[2.00000122 1.154996   0.11290953 0.60642391 0.36086309]
[1.99999942 1.41965413 2.09633986 1.14901108 1.36321143]


In [6]:
print(numpy.log10(ErrorL2["Case2/h40"]/ErrorL2["Case2/h80"])/numpy.log10(2))
print(numpy.log10(ErrorL2["Case2/h80"]/ErrorL2["Case2/h160"])/numpy.log10(2))

[1.68903605 1.19325367 0.76669934 0.58792096 0.44836991]
[2.85519908 1.49459142 1.34185048 1.38564308 1.2849791 ]


In [7]:
print(numpy.log10(ErrorL1["Case2/h40"]/ErrorL1["Case2/h80"])/numpy.log10(2))
print(numpy.log10(ErrorL1["Case2/h80"]/ErrorL1["Case2/h160"])/numpy.log10(2))

[1.34860349 1.09861279 0.77839384 0.64434036 0.57720097]
[3.30842722 1.54403224 1.23879209 1.42714006 1.33172547]
